### ISSUE TITLE
Specified types

### ISSUE THREAD

**Issue by tac0x2a** [tac0x2a/grebe#14]
Provide specified types by external structured text.

ex.

```yml
my_room : 
  - temperature : Float64
  - brightness : UInt8
```

Over write guessed types by defined specified types.
